apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-sim-data
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.data.size }}
